[mgr]
prepend_keymap = [
  { on = [
    "g",
    "i",
  ], run = "plugin lazygit", desc = "run lazygit" },
  { on = [
    "M",
    "s",
  ], run = "plugin sshfs -- menu", desc = "Open SSHFS options" },
  { on = [
    "M",
    "m",
  ], run = "plugin sshfs -- mount --jump", desc = "Mount & jump" },
  { on = [
    "M",
    "u",
  ], run = "plugin sshfs -- unmount", desc = "Unmount SSHFS" },
  { on = [
    "M",
    "j",
  ], run = "plugin sshfs -- jump", desc = "Jump to mount" },
  { on = [
    "M",
    "a",
  ], run = "plugin sshfs -- add", desc = "Add SSH host" },
  { on = [
    "M",
    "r",
  ], run = "plugin sshfs -- remove", desc = "Remove SSH host" },
  { on = [
    "M",
    "h",
  ], run = "plugin sshfs -- home", desc = "Go to mount home" },
  { on = [
    "M",
    "c",
  ], run = "cd ~/.ssh/", desc = "Go to ssh config" },
]
